format = """
$directory\
[(\\($git_branch$git_status$git_state\\) )](orange)\
$character
"""

palette = 'pzac'

[directory]
style = "red"

[character]
success_symbol = "[»](yellow)"
error_symbol = "[»](red)"

[git_branch]
format = '[$branch]($style)'
style = "orange"

[git_status]
format = '[ ($conflicted$untracked$modified$staged$renamed$deleted)($ahead_behind)](purple)'
style = "cyan"
conflicted = "C"
untracked = "?"
modified = "M"
staged = "S"
renamed = "R"
deleted = "D"
ahead = '+${count}'
diverged = '⇕+${ahead_count}-${behind_count}'
behind = '-${count}'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[palettes.pzac]
red = "160"
yellow = "226"
orange = "214"
purple = "200"
