format = """
$directory\
$git_status\
$git_state\
$git_branch\
$character
"""

[directory]
style = "160" # bright red

[character]
success_symbol = "[»](226)" # bright yellow
error_symbol = "[»](160)" # bright red

[git_branch]
format = '\([$branch]($style)\)'
style = "214" # orange

[git_status]
format = "[{($conflicted$untracked$modified$staged$renamed$deleted)($ahead_behind)}](200)"
style = "cyan"
conflicted = "C"
untracked = "?"
modified = "M"
staged = "S"
renamed = "R"
deleted = "D"
ahead = '+${count}'
diverged = '⇕+${ahead_count}-${behind_count}'
behind = '-${count}'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
